loopback_users = false
listeners.tcp.default = 5672
management.tcp.port = 15672
vm_memory_high_watermark.relative = 0.9
disk_free_limit.absolute = 1GB
deprecated_features.permit.management_metrics_collection = true